tpgns4283/TestyPie

src/main/java/com/example/testypie/user/controller/UserController.java
src/main/java/com/example/testypie/user/dto/MessageDTO.java
src/main/java/com/example/testypie/user/dto/ProfileRequestDTO.java
src/main/java/com/example/testypie/user/entity/User.java
src/main/java/com/example/testypie/user/service/UserInfoService.java

feat: 프로필 수정 구현

---

src/main/java/com/example/testypie/category/controller/CategoryController.java
src/main/java/com/example/testypie/category/dto/CategoryCreateRequestDTO.java
src/main/java/com/example/testypie/category/dto/CategoryCreateResponseDTO.java
src/main/java/com/example/testypie/category/entity/Category.java
src/main/java/com/example/testypie/category/repository/CategoryRepository.java
src/main/java/com/example/testypie/category/service/CategoryService.java
src/main/java/com/example/testypie/comment/entity/Comment.java
src/main/java/com/example/testypie/product/controller/ProductController.java
src/main/java/com/example/testypie/product/dto/ProductCreateRequestDTO.java
src/main/java/com/example/testypie/product/dto/ProductCreateResponseDTO.java
src/main/java/com/example/testypie/product/dto/ProductReadResponseDTO.java
src/main/java/com/example/testypie/product/dto/ProductUpdateRequestDTO.java
src/main/java/com/example/testypie/product/dto/ProductUpdateResponseDTO.java
src/main/java/com/example/testypie/product/entity/Product.java
src/main/java/com/example/testypie/product/repositoy/ProductRepository.java
src/main/java/com/example/testypie/product/service/ProductService.java

Category 서비스 추가

---

src/main/java/com/example/testypie/TestyPieApplication.java

#15 refactor: 오류 수정 완료

---

src/main/java/com/example/testypie/domain/category/service/CategoryService.java
src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
src/main/java/com/example/testypie/domain/comment/service/CommentService.java
src/main/java/com/example/testypie/domain/feedback/controller/FeedbackController.java
src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
src/main/java/com/example/testypie/domain/product/controller/ProductController.java
src/main/java/com/example/testypie/domain/product/dto/ProductCreateRequestDTO.java
src/main/java/com/example/testypie/domain/product/dto/ProductUpdateRequestDTO.java
src/main/java/com/example/testypie/domain/product/repositoy/ProductRepository.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/java/com/example/testypie/domain/reward/entity/Reward.java
src/main/java/com/example/testypie/domain/reward/entity/RewardImage.java
src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/resources/application.properties

#10 feat: category내의 product 전체조회(페이징), category별 product조회(페이징) 및 product, feedback, comment redirectURL수정 및 pathvariable 추가

#10 feat: category내의 product 전체조회(페이징), category별 product조회(페이징) 및 product, feedback, comment redirectURL수정 및 pathvariable 추가

---

src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
src/main/java/com/example/testypie/domain/feedback/controller/FeedbackController.java
src/main/java/com/example/testypie/domain/product/controller/ProductController.java

#10 feat: product, feedback, comment Mapping 수정

#10 feat: product, feedback, comment Mapping 수정

---

Dockerfile

#20 factor: Dockerfile

---

src/main/java/com/example/testypie/domain/category/dto/CategoryReadResponseDTO.java
src/main/resources/templates/home.html

index.html내에 카테고리 조회

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/java/com/example/testypie/domain/user/dto/ProfileResponseDTO.java
src/main/java/com/example/testypie/domain/user/entity/User.java
src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
src/main/resources/static/css/content.css
src/main/resources/static/css/header.css
src/main/resources/static/css/style.css
src/main/resources/templates/addProductForm.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/home.html
src/main/resources/templates/login.html
src/main/resources/templates/product.html
src/main/resources/templates/productList.html
src/main/resources/templates/profile.html
src/main/resources/templates/signup.html
src/main/resources/templates/updateProductForm.html
src/main/resources/templates/updateProfileForm.html

회원가입 로그인 프로필 조회 및 수정, Product CRUD 프론트까지 완성

회원가입 로그인 프로필 조회 및 수정, Product CRUD 프론트까지 완성

---

src/main/java/com/example/testypie/domain/comment/controller/CommentController.java
src/main/java/com/example/testypie/domain/comment/service/CommentService.java
src/main/java/com/example/testypie/domain/product/controller/ProductController.java
src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/resources/templates/product.html

fix: Comment Read Error 수정

---

src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java

fix : Product 작성자가 Feedback 작성하는 경우 예외처리

fix : Product 작성자가 Feedback 작성하는 경우 예외처리

---

src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/resources/static/js/category.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/login.html

#85 fix : 로그아웃 시 refresh토큰 제거되지 않는 현상 해결

#85 fix : 로그아웃 시 refresh토큰 제거되지 않는 현상 해결

---

src/main/java/com/example/testypie/domain/product/dto/ProductCreateRequestDTO.java
src/main/java/com/example/testypie/domain/product/dto/ProductPageResponseDTO.java
src/main/java/com/example/testypie/domain/product/dto/ProductReadResponseDTO.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/java/com/example/testypie/domain/scheduler/Scheduler.java
src/main/resources/static/css/header.css
src/main/resources/static/css/product.css
src/main/resources/static/css/productList.css
src/main/resources/static/css/profile.css
src/main/resources/static/css/updateProfile.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/product.html
src/main/resources/templates/productList.html
src/main/resources/templates/profile.html
src/main/resources/templates/updateProductForm.html
src/main/resources/templates/updateProfileForm.html

#85 fix : 전체적인 CSS 수정 및 날짜 포멧팅(yyyy-DD-mm)

#85 fix : 전체적인 CSS 수정 및 날짜 포멧팅(yyyy-DD-mm)

---

src/main/java/com/example/testypie/domain/comment/dto/CommentResponseDTO.java
src/main/resources/static/css/product.css
src/main/resources/templates/login.html
src/main/resources/templates/product.html
src/main/resources/templates/updateProductForm.html

#85 fix: Front 예외처리

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/java/com/example/testypie/domain/category/service/CategoryService.java
src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/java/com/example/testypie/domain/reward/service/RewardService.java
src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/java/com/example/testypie/domain/user/kakao/service/KakaoService.java
src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
src/main/java/com/example/testypie/domain/user/service/UserService.java
src/main/java/com/example/testypie/global/exception/ErrorCode.java
src/main/java/com/example/testypie/global/exception/ErrorResponse.java
src/main/java/com/example/testypie/global/exception/GlobalExceptionHandler.java

Feature kakao bugfix

---

src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/dto/ProfileRequestDTO.java
src/main/java/com/example/testypie/domain/util/S3Util.java
src/main/resources/templates/updateProfileForm.html

#85 fix: profile Image 수정

---

src/main/resources/templates/login.html

refactor: 카카오 주소 배포주소로 변경

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/resources/templates/login.html

refactor: kakao hotfix

---

src/main/java/com/example/testypie/domain/user/kakao/service/KakaoService.java
src/main/resources/templates/login.html

kakao uri 일괄 적용입니다. 나중에 application.properties로 따로 관리하겠습니다

refactor: kakao uri 정리

---

src/main/java/com/example/testypie/global/config/WebSecurityConfig.java

#85 fix: 페이지 필더단에서 열음

---

src/main/java/com/example/testypie/domain/user/dto/SignUpRequestDTO.java
src/main/resources/templates/signup.html
src/main/resources/templates/updateProfileForm.html

#85 fix: placeholder 추가

---

src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/dto/ProfileRequestDTO.java
src/main/java/com/example/testypie/domain/user/entity/User.java
src/main/java/com/example/testypie/domain/user/service/UserService.java
src/main/resources/templates/addFeedback.html
src/main/resources/templates/addProductForm.html
src/main/resources/templates/addSurvey.html
src/main/resources/templates/login.html
src/main/resources/templates/product.html
src/main/resources/templates/signup.html
src/main/resources/templates/updateProductForm.html
src/main/resources/templates/updateProfileForm.html

#85 fix: 예외처리 적용

---

src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
src/main/java/com/example/testypie/domain/category/service/CategoryService.java
src/main/java/com/example/testypie/domain/product/controller/ProductController.java
src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
src/main/java/com/example/testypie/domain/product/repository/SearchRepositoryImpl.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/resources/static/css/home.css
src/main/resources/static/js/category.js
src/main/resources/templates/home.html
src/main/resources/templates/product.html
src/main/resources/templates/productList.html

#85 feat: 좋아요별 게시물 조회기능 및 프론트 및 부모 카테고리 내 모든 게시물 조회 및 프론트

#85 feat: 좋아요별 게시물 조회기능 및 프론트 및 부모 카테고리 내 모든 게시물 조회 및 프론트

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/entity/User.java
src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
src/main/resources/templates/bugreport.html
src/main/resources/templates/product.html

#85 feat: 버그리포트 프론트 구현

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/dto/ParticipatedProductResponseDTO.java
src/main/java/com/example/testypie/domain/user/dto/RegisteredProductResponseDTO.java
src/main/java/com/example/testypie/domain/user/service/UserInfoService.java
src/main/java/com/example/testypie/global/filter/JwtAuthorizationFilter.java
src/main/resources/templates/profile.html
src/main/resources/templates/profileParticipatedProducts.html
src/main/resources/templates/profileRegisteredProducts.html
src/main/resources/templates/profileViewFeedbacks.html
src/main/resources/templates/updateProfileForm.html

Develop profile front yoosup

---

src/main/java/com/example/testypie/View/controller/ViewController.java
src/main/java/com/example/testypie/domain/bugreport/controller/BugReportController.java
src/main/java/com/example/testypie/domain/category/service/CategoryService.java
src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
src/main/java/com/example/testypie/domain/feedback/service/FeedbackService.java
src/main/java/com/example/testypie/domain/product/controller/ProductController.java
src/main/java/com/example/testypie/domain/product/dto/ProductUpdateRequestDTO.java
src/main/java/com/example/testypie/domain/product/entity/Product.java
src/main/java/com/example/testypie/domain/product/repository/ProductRepository.java
src/main/java/com/example/testypie/domain/product/service/ProductService.java
src/main/java/com/example/testypie/domain/reward/dto/RewardMapper.java
src/main/java/com/example/testypie/domain/survey/service/SurveyService.java
src/main/java/com/example/testypie/domain/user/controller/ProfileController.java
src/main/java/com/example/testypie/domain/user/controller/UserController.java
src/main/java/com/example/testypie/domain/user/dto/ParticipatedProductResponseDTO.java
src/main/java/com/example/testypie/domain/user/dto/RegisteredProductResponseDTO.java
src/main/java/com/example/testypie/domain/user/entity/User.java
src/main/java/com/example/testypie/global/exception/ErrorCode.java
src/main/java/com/example/testypie/global/filter/JwtAuthorizationFilter.java
src/main/resources/templates/addFeedback.html
src/main/resources/templates/addProductForm.html
src/main/resources/templates/bugreport.html
src/main/resources/templates/home.html
src/main/resources/templates/productList.html
src/main/resources/templates/updateProductForm.html

#85 fix: Product Create, Update 시 공백 예외처리 추가

#85 fix: Product Create, Update 시 공백 예외처리 추가

---

src/main/java/com/example/testypie/domain/feedback/repository/FeedbackRepository.java
src/main/resources/templates/login.html

카카오 로그인 리다이렉트 login.html에 추가했습니다

Develop for aws
